version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
      - RATE_LIMIT_REQUESTS=20
      - RATE_LIMIT_WINDOW=300
      - TURNSTILE_SECRET=${TURNSTILE_SECRET:-test-secret}
      - PORT=8080
    volumes:
      - ./Data:/app/Data:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=2)"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
