services:
  # Backend API
  - type: web
    name: lani-bot-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: TURNSTILE_SECRET
        value: test-secret
      - key: PORT
        value: 8080
    plan: free
    region: oregon
    healthCheckPath: /health
    autoDeploy: true

  # Frontend static site
  - type: web
    name: lani-bot-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_TURNSTILE_SITE_KEY
        value: test-key
    plan: free
    region: oregon
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
